### ISSUE TITLE
Porting UFS-WM Noah-MP baseline files to land DA workflow

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/land-DA_workflow#8]
1. Identify configuration and conversion requirement of forecast model input and output files                           
3. Restart, forcing, forecast namelist, file attributes, list of parameters, conversion/regrid and interpolation process
4. Cross compare with CDEPS functionality and requirement
5. Set up test cases (C96 and other resolutions) applicable with ufs-land-driver and UFS-WM Noah-MP
6. Reference: https://github.com/ufs-community/land-DA_workflow/issues/7

**Comment by jkbk2004** [comment]
@rhaesung Any update or progress ?

**Comment by rhaesung** [comment]
@jkbk2004 Yes, 1~3 are pretty much done and I am trying to run some test cases.

**Comment by rhaesung** [comment]
I was able to run the current land DA system using the restart files from the UFS-Noah MP regression test (datm_cdeps_lnd_gswp3). The run is /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/land-DA_workflow.

- Confirmed that the tile format of C96 restart files worked fine for skipping the vec2tile feature
- Confirmed the JEDI run 
- Confirmed the forecast model run by adding the increments

To reproduce,

The restart file needs to be edited:

-	C96 ‘slmsk’ (sea-land mask) was added for each tile from the ufs-land-driver restart file
-	‘vtype’ was renamed from ‘vegetation type’ and reformatted (missing values: 1.e+20 -> 0)  
-	renamed variables:
1.	xc -> xaxis_1
2.	yc -> yaxis_1
3.	soil_levels -> zaxis_2
4.	snow_levels -> zaxis_3
5.	snso_levels -> zaxis_4
6.	time -> Time
7.	weasd ->sheleg

**Comment by jkbk2004** [comment]
@rhaesung I am confused. Did you use ufs-wm (lnd) history outputs for the test?

**Comment by jkbk2004** [comment]
> @rhaesung I am confused. Did you use ufs-wm (lnd) history outputs for the test?
Where are the ufs-wm baseline restart files you used for the test? I expect a lot of variables must be different in gdas vector file and ufs-wm baseline restart files. What about forcing files and coupler restart files?

**Comment by rhaesung** [comment]
@jkbk2004 Yes, I used the ufs-wm baseline restart files and you can find the edited restart files and coupler restart file here: /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/landda/workdir/mem000/jedi. These restart files are renamed to run the ‘settings_DA_cycle_gdas_restart’ experiment and only the specific variables needed for snow DA are edited. For example, you can find the referred restart files from the land da vec2tile run here: /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/landda/workdir/mem000/20160101.180000.sfc_data.tile*.nc  

In this testing, I assumed the land DA is using the GDAS forcing for checking whether the forecast model runs fine with tile2vetor using the regenerated restart files.

**Comment by jkbk2004** [comment]
Why did you use ufs.cpld.lnd.out.YYYY-MM-DD-*.tile*.nc in /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/landda/workdir/mem000/jedi ? These *out* files are history files from UFS-WM baseline run.

**Comment by jkbk2004** [comment]
I see you changed ufs.cpld.lnd.out.YYYY-MM-DD-.tile.nc and renamed to 20160103.180000.sfc_data.tile1.nc. I don't get why *out* files are used.

**Comment by rhaesung** [comment]
I thought those out files from the ‘RESTART’ folder in datm_cdeps_lnd_gswp3_rst (restart reproducibility test) regression test could be used as restart files. If not, please let me know the right restart files I should consider.

**Comment by jkbk2004** [comment]
OK! you used rst baseline.

**Comment by jkbk2004** [comment]
@rhaesung Please, follow up all the way thru to cross check all other comparisons: parameters and variables in gdas IC, forcings, coupler and cdeps files.

**Comment by rhaesung** [comment]
1. IC
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

UFS-land-driver | UFS-WM NoahMP App
-- | --
file name: <BR>ufs-land_C96_init_fields_1hr.nc | file name: <BR>ufs-land_C96_init_fields.tile1.nc
dimensions: <BR>date_length = 19 ;<BR>location = 18322 ;<BR>soil_levels = 4 ; | dimensions: <BR>lat = 96 ;<BR>lon = 96 ;<BR>soil_levels = 4 ;
variables: <BR>time, "seconds since 1970-01-01 00:00:00"<BR>latitude, "degrees_north"<BR>longitude, "degrees_east"<BR>snow_water_equivalent, "mm"<BR>snow_depth, “m”<BR>canopy_water, “mm”<BR>skin_temperature, “K”<BR>soil_temperature, “K”<BR>soil_moisture, “m3/m3”<BR>soil_liquid, “m3/m3”<BR>soil_level_thickness, “m”<BR>soil_level_nodes, “m” | variables: <BR>time, "seconds since 1970-01-01 00:00:00"<BR>geolat, "degrees_north"<BR>geolon, "degrees_east"<BR>snow_water_equivalent, “mm”<BR>snow_depth, “m”<BR>canopy_water, “mm”<BR>skin_temperature, “K”<BR>soil_temperature, “K”<BR>soil_moisture, “m3/m3”<BR>soil_liquid, “m3/m3”

</html>

2. Static files

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

UFS-land-driver | UFS-WM NoahMP App
-- | --
ufs-land_C96_static_fields.nc<BR>C96_grid.tile*.nc<BR>C96_ oro_data.tile*.nc<BR>Oro_C96.mx100.tile*.nc | C96_grid.tile*.nc<BR>C96.initial.tile*.nc<BR>C96.maximum_snow_albedo.tile*.nc<BR>C96_mosaic.nc<BR>C96.slope_type.tile*.nc<BR>C96.soil_type.tile*.nc<BR>C96.substrate_temperature.tile*.nc<BR>C96.vegetation_greenness.tile*.nc<BR>C96.vegetation_type.tile*.nc<BR>oro_data.tile*.nc

</html>

3. Forcing

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

UFS-land-driver, GDAS | UFS-WM NoahMP App, GSWP3
-- | --
dimensions: <BR>time = 24 ;<BR>location = 18322 ; | file names: <BR>clmforc.GSWP3.c2011.0.5x0.5.Prec.2000-01.nc<BR>clmforc.GSWP3.c2011.0.5x0.5.Solr.2000-01.nc<BR>clmforc.GSWP3.c2011.0.5x0.5.TPQWL.2000-01.nc<BR>clmforc.GSWP3.c2011.0.5x0.5.TPQWL.SCRIP.210520_ESMFmesh.nc
variables: <BR>solar_radiation, "W/m2"<BR>time, "seconds since 1970-01-01 00:00:00"<BR>longwave_radiation, "W/m2"<BR>temperature, "K"<BR>specific_humidity, "kg/kg"<BR>wind_speed, "m/s"<BR>surface_pressure, "Pa"<BR>precipitation_bilinear, "mm/s"

</html>

4. CDEPS Inputs

fv1.9x2.5_141008_ESMFmesh.nc
topodata_0.9x1.25_USGS_070110_stream_c151201.nc
topodata_0.9x1.SCRIP.210520_ESMFmesh.nc

5. Coupler

See the section 1.3.5 in https://noaa-emc.github.io/noahmp/DriverAndCoupling.html

**Comment by rhaesung** [comment]
New action items:

- Need a new test using the same forcing (i.e., ERA5) for both UFS-land-driver and UFS-WM-NoahMP with the updated land mask 
- PSL's develop now uses the updated land mask and newer JEDI version. Need to check with that

**Comment by rhaesung** [comment]
I was able to run the 'hera.singularity' baseline with the restart files from the UFS-Noah MP regression test (datm_cdeps_lnd_era5). The run is /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/land-DA_workflow.
Reference: https://github.com/ufs-community/land-DA_workflow/issues/21

- Confirmed that the tile format of C96 ERA5 restart files worked fine for skipping the vec2tile feature
- Confirmed the JEDI run 
- Confirmed the forecast model run by adding the increments

To reproduce,

The restart file needs to be edited:

-	C96 ‘slmsk’ (sea-land mask) was added for each tile from the ufs-land-driver restart file
-	‘vtype’ was renamed from ‘vegetation type’ and reformatted (missing values: 1.e+20 -> 0)  

- 'Time' variable was renamed from 'time' and the dimension was changed from 'UNLIMITED' to 1. 

-	renamed variables:
1.	grid_xt -> xaxis_1
2.	grid_yt -> yaxis_1
3.	soil_levels -> zaxis_2
4.	snow_levels -> zaxis_3
5.	snso_levels -> zaxis_4
6.	weasd ->sheleg

**Comment by rhaesung** [comment]
#21

**Comment by rhaesung** [comment]
Currently, the 'read and write the perturbation pattern' feature resides in the vec2tile submodule. For this option, a new file will be created with the perturbations and lat lon only.

If we want to use this feature in future releases, we need to come back and check the vec2tile submodule.

**Comment by rhaesung** [comment]
I was able to reproduce the JEDI (skylab v4.0) run using UW land model restart tile files. The test directory is on Hera (/scratch2/NCEPDEV/stmp/Rhaesung.Kim/test).

In this experiment, 

- The vector format restart file is no longer used.
- Restart tile files from the UFS WM land model are directly read without using 'vec2tile'. These input tiles are located in /scratch2/NCEPDEV/stmp/Rhaesung.Kim/test/workdir/mem000/jedi.
- The edited input tiles (https://github.com/ufs-community/land-DA_workflow/issues/8#issuecomment-1587356979) are used in JEDI.
- After the JEDI run, the 'tile2vector' is still used in DA_update and ufs-land-driver.
