### ISSUE TITLE
Automatic documentation build test fails

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/land-DA_workflow#80]
The Land DA automatic documentation build test fails with the following message:
![git_error](https://github.com/ufs-community/land-DA_workflow/assets/60152248/3bf35017-110b-47a1-99ff-153f37dfa8c4)

It is searching for `docs`, but it was renamed to `doc`.

**Comment by chan-hoo** [comment]
@gspetro-NOAA, as described above, the github action for `Build HTML` fails due to missing `docs`. Can you let me know where I can change it to `doc`?

**Comment by gspetro-NOAA** [comment]
@chan-hoo We might need @jkbk2004 's input on this. I already changed `docs` to `doc` in [`.github/workflows/auto_doc.yml`](https://github.com/ufs-community/land-DA_workflow/blob/develop/.github/workflows/auto_doc.yml), except in the artifact output name (html-docs), which I don't think affects anything (I could be wrong). I am not too familiar with GitHub Actions to know where else it could be pulling the name `docs` from because I don't see `docs` anywhere else in either YAML, so it must be coming from another place... Maybe the GitHub Actions container? I'm not sure where/how that's configured. 
Another thing to consider is whether we even need the doc build tests now that we have toggled on the RTD build for documentation with each PR. That RTD build is free to us, so it might be better to save on GitHub Actions resources for now. At some point, I'd like to add additional documentation tests (like running the linkchecker), which the RTD build doesn't do, but currently, the GitHub Actions doc build just duplicates what the RTD build test is doing.

**Comment by chan-hoo** [comment]
@gspetro-NOAA, yes, I think so too. I couldn't find `Building docs in docs/` in any files of the repo either. The sphinx-action build is done somewhere outside the repo. @jkbk2004, can you let us know how to change the script used for the sphinx-action?

**Comment by jkbk2004** [comment]
I think sometime work sometime not: https://github.com/ufs-community/land-DA_workflow/actions/runs/8251075176

**Comment by jkbk2004** [comment]
API itself a bit old: https://github.com/ammaraskar/sphinx-action

**Comment by jkbk2004** [comment]
People still use the API: https://stackoverflow.com/questions/73532719/using-github-actions-to-deploy-sphinx-documentation

**Comment by jkbk2004** [comment]
doc or docs issue?

**Comment by chan-hoo** [comment]
Yes. The sphinx-action build script is searching for `docs` instead of `doc`.

**Comment by jkbk2004** [comment]
> Yes. The sphinx-action build script is searching for `docs` instead of `doc`.

sounds like we need to put docs back.

**Comment by chan-hoo** [comment]
According to the NCO standards, it should be `doc`.

**Comment by jkbk2004** [comment]
I think time to update NCO standards. I prefer doc as well. Then, we should build our own git api: just one tweak of https://github.com/ammaraskar/sphinx-action. Updating the api will be interesting as well.

**Comment by chan-hoo** [comment]
Now `doc` is detected by the yaml file, but I have another issue:
```
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not find a version that satisfies the requirement alabaster==0.[7](https://github.com/ufs-community/land-DA_workflow/actions/runs/8453347427/job/23155813510?pr=81#step:4:8).16 (from -r doc/requirements.txt (line 7)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.7.12, 0.7.13)
ERROR: No matching distribution found for alabaster==0.7.16 (from -r doc/requirements.txt (line 7))
WARNING: You are using pip version 20.0.2; however, version 24.0 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
``` 
Any idea?

**Comment by jkbk2004** [comment]
@gspetro-NOAA a trouble with https://github.com/ufs-community/land-DA_workflow/blob/develop/doc/requirements.txt#L7C1-L7C18 ?

**Comment by jkbk2004** [comment]
Or install alabaster==0.7.16 in python- pip install ?

**Comment by chan-hoo** [comment]
It requires to update the `pip` version, but I don't have permission.

**Comment by jkbk2004** [comment]
I think the gitaction api uses python from git runner. If thta's the case, we should be able to install thru our own gitaction yml.
